// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjOMwAuzmn1KPSa59sSXwOr3hHjW16YE',
    appId: '1:176980771513:web:f926f30e261763eecd1168',
    messagingSenderId: '176980771513',
    projectId: 'perfumeria-6c977',
    authDomain: 'perfumeria-6c977.firebaseapp.com',
    storageBucket: 'perfumeria-6c977.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHEDSsA3gyZt3oC9nCxAMah5ot7L1RTPM',
    appId: '1:176980771513:android:a0935c0cf1e62703cd1168',
    messagingSenderId: '176980771513',
    projectId: 'perfumeria-6c977',
    storageBucket: 'perfumeria-6c977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUY-3obDEM1YxnNvCGtlj-CP0ibSuESw',
    appId: '1:176980771513:ios:1c41034a508a3154cd1168',
    messagingSenderId: '176980771513',
    projectId: 'perfumeria-6c977',
    storageBucket: 'perfumeria-6c977.firebasestorage.app',
    iosBundleId: 'com.example.perfumeriacrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtUY-3obDEM1YxnNvCGtlj-CP0ibSuESw',
    appId: '1:176980771513:ios:1c41034a508a3154cd1168',
    messagingSenderId: '176980771513',
    projectId: 'perfumeria-6c977',
    storageBucket: 'perfumeria-6c977.firebasestorage.app',
    iosBundleId: 'com.example.perfumeriacrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWjOMwAuzmn1KPSa59sSXwOr3hHjW16YE',
    appId: '1:176980771513:web:4bd165563addab88cd1168',
    messagingSenderId: '176980771513',
    projectId: 'perfumeria-6c977',
    authDomain: 'perfumeria-6c977.firebaseapp.com',
    storageBucket: 'perfumeria-6c977.firebasestorage.app',
  );
}
